<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Video</name>
   <tag></tag>
   <elementGuidId>22324df9-61a8-4ddf-a1ca-f108cf97edb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.main-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-page']/header/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Video&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>b80a46bd-67ed-4a67-851f-61b8415ef2ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main-title</value>
      <webElementGuid>e1258537-c74e-4d52-8c53-593abb5103b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Video</value>
      <webElementGuid>188281af-73a8-4ce6-a36e-96b7207b852b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-page&quot;)/header[@class=&quot;app-header&quot;]/div[@class=&quot;labels&quot;]/h1[@class=&quot;main-title&quot;]</value>
      <webElementGuid>8a1b31e4-bfd1-4346-8104-d79bf218d488</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-page']/header/div/h1</value>
      <webElementGuid>1bd65983-e811-43d2-b059-6089e033c6b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log out'])[1]/following::h1[1]</value>
      <webElementGuid>52a8ebae-b06d-4ae8-b4c1-70b2516c5e28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='fullLocator'])[1]/following::h1[1]</value>
      <webElementGuid>abc7725a-12eb-47f1-84d7-029be6f7fc50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>c39659bd-ff47-42d1-80b2-9a5106cb0370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Video' or . = 'Video')]</value>
      <webElementGuid>aef0e15a-7b6d-4cfa-9348-731b6648ef1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
