<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Panel</name>
   <tag></tag>
   <elementGuidId>d5c78d4c-14a5-46f7-b5b9-07abbedbe1bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.title</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Panel' or . = 'Panel')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value> //*[@class='title' and text()=&quot;Panel&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Panel&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>89ae2f54-590d-44e5-8636-ed8389b8c453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>b57cb4cd-b05b-447b-ace4-00dc73c810e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>a71a88dd-2851-4e55-a85e-1259a198e81a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>dc2d8fc6-ead3-41eb-8e56-74764daf78f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>cb0366b3-3b1e-4adf-89b6-8dabf68edbb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>0823918d-1854-4653-8ae3-6eb361bd1dc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>f7904f3e-4d79-4a0f-bdac-cf11cdedd17a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
