<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Panel</name>
   <tag></tag>
   <elementGuidId>d5c78d4c-14a5-46f7-b5b9-07abbedbe1bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='app-content']/div[2]/div/div/div/section[2]/div/div/div/div/div/label/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Panel&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e59baa80-2a56-4079-a6f9-24ab71b8da77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>8bbdd094-067f-4bbf-9b8c-b99af4775c2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Panel</value>
      <webElementGuid>d8cd6ab4-5b72-4cda-8708-13d840a797d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-content&quot;)/div[@class=&quot;page-view&quot;]/div[@class=&quot;page-view-container use-default-styles md&quot;]/div[@class=&quot;page-view-content&quot;]/div[1]/section[2]/div[@class=&quot;fieldset-content&quot;]/div[@class=&quot;device-access-item-groups&quot;]/div[@class=&quot;device-access-item-group-wrapper device-access-toggle&quot;]/div[@class=&quot;device-access-item&quot;]/div[@class=&quot;simple-binary is-toggle&quot;]/label[1]/div[@class=&quot;title&quot;]</value>
      <webElementGuid>598c0e89-69ef-454c-85e6-38f34daa6918</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='app-content']/div[2]/div/div/div/section[2]/div/div/div/div/div/label/div</value>
      <webElementGuid>8561d1bb-bcfd-41df-ac95-177291654a33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Security Panels'])[1]/following::div[4]</value>
      <webElementGuid>81a6f6ab-1da9-40a2-9fee-3ab2d60ca909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Locks'])[1]/preceding::div[2]</value>
      <webElementGuid>8e613f05-27cb-41b9-9f26-8658784411e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Front Door'])[1]/preceding::div[2]</value>
      <webElementGuid>fc3d07f0-306d-4417-9ca0-db9078e8642e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Panel']/parent::*</value>
      <webElementGuid>4a6ba703-53ff-4922-b51e-7c525490c881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div</value>
      <webElementGuid>2fc64613-e865-47ce-91c2-d7a178262d33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Panel' or . = 'Panel')]</value>
      <webElementGuid>97791770-cf42-4090-bf35-4365edd7570c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
