<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First Name_ember790-first-name</name>
   <tag></tag>
   <elementGuidId>be996464-1425-4b8c-9fda-0d2535d7d9b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ember790-first-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ember790-first-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;First Name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9654a584-03fa-4c63-a7ef-affdf0678374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ember790-first-name</value>
      <webElementGuid>2dd95826-0cd4-462f-8fc3-b5e25088de19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ember-text-field ember-view</value>
      <webElementGuid>8747d490-dca2-40bd-b073-dde4dcd09133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>First Name</value>
      <webElementGuid>e2cee107-2e7c-4d21-8641-ef3340c84193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>09e7192b-652c-4e81-9073-8e21bc5c1cc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ember790-first-name&quot;)</value>
      <webElementGuid>1b8651b8-1f01-45c3-a288-bcdbe33ccd96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ember790-first-name']</value>
      <webElementGuid>28681113-d901-42b0-a784-95be380639d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ember787']/section[2]/fieldset/div/div/input</value>
      <webElementGuid>19b5b820-7c21-4788-b3aa-3ec776fbb5a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>968c4100-e497-46b8-b383-14619f47cdac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ember790-first-name' and @placeholder = 'First Name' and @type = 'text']</value>
      <webElementGuid>6914911a-9394-492d-9609-9d17fad45402</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
