<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Name_ember790-last-name</name>
   <tag></tag>
   <elementGuidId>58b893a4-fadd-41b0-b90e-4d6b88a20088</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ember790-last-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ember790-last-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Last Name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5cb1d134-a814-46b5-8d2d-466e5070c351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ember790-last-name</value>
      <webElementGuid>62cc1121-6e94-416b-b532-ff480594c7b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ember-text-field ember-view</value>
      <webElementGuid>45e53feb-1b64-4320-8238-50c517e23805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last Name</value>
      <webElementGuid>8f6826f8-2019-48f8-bdb6-d0d7a5e12f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fb056ea5-b5be-4ec4-aca7-3e7a4254c5aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ember790-last-name&quot;)</value>
      <webElementGuid>2b7f4dc0-1773-47a8-b7a1-67eb28fe0ace</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ember790-last-name']</value>
      <webElementGuid>34040873-2109-4844-8de9-57c60b920db6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ember787']/section[2]/fieldset/div[2]/div/input</value>
      <webElementGuid>e660772d-f743-4ad5-b16a-2c1ac35fe330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>ab536d4a-b3a6-4e98-b64f-f3b1e7005401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ember790-last-name' and @placeholder = 'Last Name' and @type = 'text']</value>
      <webElementGuid>60dc17bd-1ad4-4a3c-bc7e-0bee9ea3a8b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
