<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-Login</name>
   <tag></tag>
   <elementGuidId>fc8e4e7e-f66f-4cd8-8da1-46eaf8ad0928</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signInButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#signInButton</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'submit' and @name = 'ctl00$ContentPlaceHolder1$loginform$signInButton' and @id = 'signInButton' and @title = 'Login to your account.']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Log In&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>91cdd0e4-04a1-4875-8970-ad8dd5ec2ea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>cc2a6639-e292-456e-842c-36c305ffe6f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>94d1fab6-ae2b-4340-9a5b-6cf56c015991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>96c32737-c989-470c-8e3e-6ef2f331938f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
