<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-Login</name>
   <tag></tag>
   <elementGuidId>fc8e4e7e-f66f-4cd8-8da1-46eaf8ad0928</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signInButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signInButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Log In&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07cacd0f-f831-4618-ab88-0c8e0bd6b628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>8e965586-195b-4729-9a8f-d884a4dd5545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$loginform$signInButton</value>
      <webElementGuid>310096ec-91c8-4ee9-bedb-095f4dc36eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Log In</value>
      <webElementGuid>c315899e-cd4b-4432-911c-71015359aa54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ContentPlaceHolder1$loginform$signInButton&quot;, &quot;&quot;, false, &quot;&quot;, &quot;https://www.alarm.test-us.adcinternal.com/web/Default.aspx&quot;, false, false))</value>
      <webElementGuid>9b2e2bf1-77a6-4eb4-b50e-4cf051c3d9d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signInButton</value>
      <webElementGuid>3b1a5a71-dcd0-4e7a-a013-b472ed9dc722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Login to your account.</value>
      <webElementGuid>316c0ea3-f324-4027-b239-25b34586731b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button btn-sign-in</value>
      <webElementGuid>ef9bf1ec-991c-4577-883f-1d8e8cf88de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loading-text</name>
      <type>Main</type>
      <value>Logging In...</value>
      <webElementGuid>fca32d85-7616-4165-837e-a16187fb7cc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signInButton&quot;)</value>
      <webElementGuid>b6dfb0f2-d834-4982-bbb2-ef6ac77e67ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signInButton']</value>
      <webElementGuid>933a9618-47f4-4259-9582-3afce169fa97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder1_loginform_loginFormControl']/div/div/div[2]/div[2]/input</value>
      <webElementGuid>cfeee090-2103-4df7-9d2a-faef401f5d8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>96280c3b-3c4e-498b-bbfa-b111c114389d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$ContentPlaceHolder1$loginform$signInButton' and @id = 'signInButton' and @title = 'Login to your account.']</value>
      <webElementGuid>e717d37a-f361-4a3f-887f-f9b36fdfdc3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
