<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Save</name>
   <tag></tag>
   <elementGuidId>f2648122-8721-4d0b-895e-f6ca7deadc2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_responsiveBody_NotificationEditControl_btnSaveNotification</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_responsiveBody_NotificationEditControl_btnSaveNotification']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Save&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ddb158a-aea4-4ee5-9aef-cfa397d5aad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d8b99de2-912f-4f69-982a-6eb4568e8b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$responsiveBody$NotificationEditControl$btnSaveNotification</value>
      <webElementGuid>2508075e-0419-4360-9867-703b8f2b6d96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>518696be-9978-4790-adaa-808e553611e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_responsiveBody_NotificationEditControl_btnSaveNotification</value>
      <webElementGuid>173db97d-0809-40bc-b3d9-ace755494f81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-save ellipsize</value>
      <webElementGuid>304d851a-90f5-4a38-b4af-36d006cc0463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_responsiveBody_NotificationEditControl_btnSaveNotification&quot;)</value>
      <webElementGuid>20ec4481-1863-4d3c-9601-8969fc39fce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Notification  Alarm.com/iframe_Notifications  Alarm.com has loaded_ember180</value>
      <webElementGuid>b0965735-eda7-412c-98c5-30014ff3204b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_responsiveBody_NotificationEditControl_btnSaveNotification']</value>
      <webElementGuid>9039bc7d-d050-41f6-b15c-b65676413b79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_responsiveBody_NotificationEditControl_legacyActionButtons']/input</value>
      <webElementGuid>810a1a8d-a0ad-4432-a9e9-01004da5ee2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[78]/input</value>
      <webElementGuid>af644882-c0f3-4007-a8bf-b6271e1a22a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$responsiveBody$NotificationEditControl$btnSaveNotification' and @id = 'ctl00_responsiveBody_NotificationEditControl_btnSaveNotification']</value>
      <webElementGuid>2bf01380-ccee-483b-9e77-e0ef4e456cc6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
