<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Notifications  Alarm.com has loaded_ember180 (1)</name>
   <tag></tag>
   <elementGuidId>cc82362a-f98a-42da-bccb-4f0c719461fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ember180</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ember180']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[title=&quot;Notifications&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>2289b7a7-fb24-448c-b4b4-649d5e77f36c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ember180</value>
      <webElementGuid>7b30b94e-041f-4aa4-bd0a-3e4cf5d15927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-iframe ember-view</value>
      <webElementGuid>f310092f-d439-444e-9d7e-56d7d8e13eac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Notifications</value>
      <webElementGuid>e222aeea-73d3-4b44-bed4-849525299888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/web/Notifications/NotificationsNew.aspx</value>
      <webElementGuid>c9aefaa1-ca31-42e5-97e7-9ff319f1f1a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ember180&quot;)</value>
      <webElementGuid>3462e681-994e-4d25-84af-1d8129cb59a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ember180']</value>
      <webElementGuid>28d53cac-fdfe-4974-b7fe-32150e99a2cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='app-content']/div[2]/iframe</value>
      <webElementGuid>9069827a-5112-4bfc-99e8-64ce7bd61906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>4a21c482-a371-4495-bd1c-f4836011fdeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ember180' and @title = 'Notifications' and @src = '/web/Notifications/NotificationsNew.aspx']</value>
      <webElementGuid>9f0659c4-af0e-4af2-a781-1a4a8e3bf9fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
