<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Notification</name>
   <tag></tag>
   <elementGuidId>6b7217fa-47db-4a63-9370-e16bd499ac77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_responsiveBody_NotificationEditControl_txtNotificationName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_responsiveBody_NotificationEditControl_txtNotificationName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Notification name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>82705813-2cc6-4e81-a63e-2ef41d8029fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$responsiveBody$NotificationEditControl$txtNotificationName</value>
      <webElementGuid>dc427b3e-f229-47b9-808a-612b8d063647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ff6cbdd8-cc8a-446b-9b9c-ab5bd50066a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_responsiveBody_NotificationEditControl_txtNotificationName</value>
      <webElementGuid>d234db6f-cc27-490f-be4c-672a09950b42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bootstrap form-control span12 </value>
      <webElementGuid>854cc827-9a47-4ea9-8b39-c4e85c632cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Notification name</value>
      <webElementGuid>599729b5-c726-48ac-8f10-373988ff22b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Arming Event</value>
      <webElementGuid>132d80f8-9b8e-439e-a526-1c98b3f18439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_responsiveBody_NotificationEditControl_txtNotificationName&quot;)</value>
      <webElementGuid>4921219b-10f1-4375-888b-b8c197ab43f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Notification  Alarm.com/iframe_Notifications  Alarm.com has loaded_ember180</value>
      <webElementGuid>40dad1d3-00f7-4a15-90c4-8b0758623999</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_responsiveBody_NotificationEditControl_txtNotificationName']</value>
      <webElementGuid>dcc7f5bf-0d8f-49d4-8f68-c6b4c76e6654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_responsiveBody_NotificationEditControl_notificationEditControl']/div[2]/div/div/input</value>
      <webElementGuid>eee482c0-d470-43ec-971b-fe08c00c97ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>6430123f-789b-4cae-93af-bec8c594dc75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$responsiveBody$NotificationEditControl$txtNotificationName' and @type = 'text' and @id = 'ctl00_responsiveBody_NotificationEditControl_txtNotificationName' and @placeholder = 'Notification name']</value>
      <webElementGuid>0d0274b2-9386-46c6-8da2-221695a64527</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
