<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Disarm (1)</name>
   <tag></tag>
   <elementGuidId>d8c5360f-60ff-4ec5-ade3-f74dfaf1ed11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.span2 > span.style-checkbox > label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;ctl00_responsiveBody_NotificationEditControl_armingActionsBlock&quot;)/div[@class=&quot;row-fluid no-min-height arming-actions-list&quot;]/div[@class=&quot;row-fluid min-height-20&quot;]/div[@class=&quot;span2&quot;]/span[@class=&quot;style-checkbox&quot;]/label[1][count(. | //*[@for = 'ctl00_responsiveBody_NotificationEditControl_chkDisarm' and @ref_element = 'Object Repository/Page_Notification  Alarm.com/iframe_Notifications  Alarm.com has loaded_ember180']) = count(//*[@for = 'ctl00_responsiveBody_NotificationEditControl_chkDisarm' and @ref_element = 'Object Repository/Page_Notification  Alarm.com/iframe_Notifications  Alarm.com has loaded_ember180'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@for=&quot;ctl00_responsiveBody_NotificationEditControl_chkDisarm&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Disarm&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>2e07a49e-75a8-467c-8b19-ac9d278795af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>bcc97544-1499-404f-b388-d3d58806c920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>f9f8d090-687e-4a2e-8980-73c710992404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>0a5086b2-fc9e-451f-9ab7-c6617532e559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>c8692337-5df2-47e6-bc26-cb09113b2ca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>e3ab1f49-f291-46fb-bc26-8e19a64f1652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>1d0f5378-1e58-4849-9963-267ad48e8358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>1811d77e-4b9a-4276-8d32-b81ab39ab806</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
