<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Add</name>
   <tag></tag>
   <elementGuidId>ae9e345e-b8c3-4583-9bf7-463bb6cb65a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_responsiveBody_NotificationEditControl_recipients_addRecipient</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ctl00_responsiveBody_NotificationEditControl_recipients_addRecipient']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; Add&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>67c4e066-9026-45a5-bc6b-aa9ac6dd4fd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_responsiveBody_NotificationEditControl_recipients_addRecipient</value>
      <webElementGuid>7f73e087-fa5d-4b37-8f30-521dfe6f3b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bf4fff42-5ed4-4442-813f-e97207200cb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary pull-right add-recipient-btn</value>
      <webElementGuid>8524c077-1baf-45ca-aec0-2ea4568805d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#addressBookModal</value>
      <webElementGuid>ccf7b5e4-0f6a-4416-8635-4b5edaf6a177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b83b2684-432f-40b7-abed-794e92b02986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>65570b05-ff07-4054-a061-76730877580e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    
                    Add
                </value>
      <webElementGuid>8ecf7153-6bff-41ec-8cd6-9eefdafc9980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_responsiveBody_NotificationEditControl_recipients_addRecipient&quot;)</value>
      <webElementGuid>a915730e-8cb5-4803-8b46-da8b514a06f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Notification  Alarm.com/iframe_Notifications  Alarm.com has loaded_ember180</value>
      <webElementGuid>6b5b0f10-69f0-43ef-9f53-1299e9aaa8ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ctl00_responsiveBody_NotificationEditControl_recipients_addRecipient']</value>
      <webElementGuid>b8b7ba81-63dd-40dc-9629-23bea3fa5509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='addRecipientBtnWrap']/span</value>
      <webElementGuid>2cd4fc79-2fe9-46b0-a813-53997f6dea09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recipients:'])[1]/following::span[1]</value>
      <webElementGuid>cacc1025-883b-4c5f-9fa7-85eb553f5e6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Note:'])[1]/preceding::span[1]</value>
      <webElementGuid>9ed61614-996f-40a7-bbd0-b6417fab1004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add']/parent::*</value>
      <webElementGuid>7da8364f-2a70-4789-b052-3db12795a451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[76]/div/div/div/div/div[2]/span</value>
      <webElementGuid>80401843-40c3-4009-bdc8-b3e8d3ae1f67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ctl00_responsiveBody_NotificationEditControl_recipients_addRecipient' and @href = '#addressBookModal' and (text() = '
                    
                    Add
                ' or . = '
                    
                    Add
                ')]</value>
      <webElementGuid>77c78aee-320a-4af0-a8d8-06221bfd554a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
