<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_New Notification</name>
   <tag></tag>
   <elementGuidId>789d7b96-f31a-465c-a184-aa3e51e7479c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_responsiveBody_notifications_btnAddNotification</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ctl00_responsiveBody_notifications_btnAddNotification']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; New Notification&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0247dcc2-936e-492e-a95b-bc4b3946fdd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_responsiveBody_notifications_btnAddNotification</value>
      <webElementGuid>182b3fc8-d5b1-4ce5-8eab-654394b56faf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#notificationCatalog</value>
      <webElementGuid>ebe32dad-532c-44da-8556-fb3f3c9dca1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary pull-right notification-catalog-launcher</value>
      <webElementGuid>0eb29248-3c5c-412d-9164-2cb2f7fa2850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>06664253-322c-4d05-8b00-b06364781b1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            New Notification
        </value>
      <webElementGuid>fe36afb6-a898-4f56-b595-35d8ed5c1d6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_responsiveBody_notifications_btnAddNotification&quot;)</value>
      <webElementGuid>08d5a61f-e947-4c29-b94e-d926e27a9acc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Notifications  Alarm.com/iframe_Notifications  Alarm.com has loaded_ember180</value>
      <webElementGuid>d780c80d-2394-4c85-b8cc-46366420aa80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ctl00_responsiveBody_notifications_btnAddNotification']</value>
      <webElementGuid>b6b7c7ae-d908-46a0-8044-736e169ba5dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='ctl00_responsiveBody_notifications_spNewNotification']/button</value>
      <webElementGuid>c2ae8b2a-3e8b-4a9d-984d-a1b9471d4d2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[1]/following::button[1]</value>
      <webElementGuid>69bec0fb-5a3a-4505-a24e-8eba7358afba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/following::button[1]</value>
      <webElementGuid>600e4804-3149-487c-b885-10f2ab484a0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suggested'])[1]/preceding::button[1]</value>
      <webElementGuid>6322f59f-103a-4b60-82cf-5cd45536f01d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>eaeddaa1-524e-4226-b3e8-f030a07f1d48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'ctl00_responsiveBody_notifications_btnAddNotification' and (text() = '
            New Notification
        ' or . = '
            New Notification
        ')]</value>
      <webElementGuid>6f35e898-4bf0-41d5-a2ee-aeb21ea277c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
