<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_New Notification</name>
   <tag></tag>
   <elementGuidId>789d7b96-f31a-465c-a184-aa3e51e7479c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_responsiveBody_notifications_btnAddNotification</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'ctl00_responsiveBody_notifications_btnAddNotification' and (text() = '
            New Notification
        ' or . = '
            New Notification
        ') and @ref_element = 'Object Repository/Page_Notifications  Alarm.com/iframe_Notifications  Alarm.com has loaded_ember180']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ctl00_responsiveBody_notifications_btnAddNotification']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; New Notification&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>49023603-4e16-4f15-9d44-8608db8fee44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>0cb40161-1380-4e5f-bf2b-8b7d388de1d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>a2833a48-a1ed-4d69-b335-95eb25b21c08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>fe6c7fd1-4c5f-429a-9f20-52ecb0824fd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>57290011-7326-40c7-be92-8bbf0d76dad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>1dd82ebe-eff0-4a73-bc72-65ec8f5af6c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>84297735-e329-4abf-9e7c-e983e7b4039d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
