<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Notifications  Alarm.com has loaded_ember9</name>
   <tag></tag>
   <elementGuidId>18966363-d883-4e60-999e-d5b8df06e1a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ember9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@class=&quot;page-iframe ember-view&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'ember9' and @class = 'page-iframe ember-view' and @title = 'Notifications' and @src = '/web/Notifications/NotificationsNew.aspx']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[title=&quot;Notifications&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>f75b8a7b-399c-44bf-863f-dc80b659933c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ember9</value>
      <webElementGuid>4dd05e7b-8471-44bf-9e34-571e80932fb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-iframe ember-view</value>
      <webElementGuid>6b2f6687-0174-415e-90ab-63df89ffd5db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Notifications</value>
      <webElementGuid>74d9eaa7-de08-42c8-b75a-70b5af65279e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/web/Notifications/NotificationsNew.aspx</value>
      <webElementGuid>587de89b-54de-416c-bd1b-f3f96d5bcedb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ember9&quot;)</value>
      <webElementGuid>7dd2dab6-84c2-48cf-99f6-c03a37606707</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ember9']</value>
      <webElementGuid>4d7c63ba-e019-4d5a-8700-3cd34982bcf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='app-content']/div[2]/iframe</value>
      <webElementGuid>b9e6207f-2325-4c1f-885b-c8370af4853d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>574fcc4d-00ab-41db-9969-8a932bb92d0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ember9' and @title = 'Notifications' and @src = '/web/Notifications/NotificationsNew.aspx']</value>
      <webElementGuid>83079c19-bf8b-4e6a-b8b8-1faabd7fd122</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
