<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Notifications  Alarm.com has loaded_ember180</name>
   <tag></tag>
   <elementGuidId>14157f7a-41f7-42c8-96a1-31c1164d58cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ember180</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ember180']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[title=&quot;Notifications&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>d154c290-adf4-4b49-8fe3-673a6874ce3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ember180</value>
      <webElementGuid>959fccb8-bcd1-4923-803f-2d26f1c642ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-iframe ember-view</value>
      <webElementGuid>c9e4a817-104d-4496-a3c4-69aa3f37ed94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Notifications</value>
      <webElementGuid>a006b3aa-dd71-4b26-a1f9-7347b2db4252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/web/Notifications/NotificationsNew.aspx</value>
      <webElementGuid>4b724458-3066-48d4-b513-420a6e8d5049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ember180&quot;)</value>
      <webElementGuid>9804b687-49ec-4652-b22a-34d77cea65ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ember180']</value>
      <webElementGuid>63499a8c-d171-42a5-8aa4-cd32dad55cc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='app-content']/div[2]/iframe</value>
      <webElementGuid>c015e81c-ff92-40cb-b93a-dfc5aabce1b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>531974ec-f1a3-405d-8a64-5e74a29e4f6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ember180' and @title = 'Notifications' and @src = '/web/Notifications/NotificationsNew.aspx']</value>
      <webElementGuid>403408bc-3276-4f3d-8b82-b2f5291dbb24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
