<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Notifications  Alarm.com has loaded_ember179</name>
   <tag></tag>
   <elementGuidId>f86eab7c-18fa-488b-afb0-2c71dbe132a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ember179</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ember179']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[title=&quot;Notifications&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>14078c4b-3bc3-4fd8-9529-9e8cbf39c025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ember179</value>
      <webElementGuid>5847cbcd-38aa-45cd-978c-ddef0bc32dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-iframe ember-view</value>
      <webElementGuid>5b2bfb7f-b7a6-41f3-838f-ae3b4e2bc128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Notifications</value>
      <webElementGuid>24e566a7-eeec-407b-8d9e-ffb6305fe8f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/web/Notifications/NotificationsNew.aspx</value>
      <webElementGuid>9cf70aec-78b2-4457-aad2-7db581ca2f3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ember179&quot;)</value>
      <webElementGuid>cb3505c9-f6c5-4da6-8fab-ec03731b4d19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ember179']</value>
      <webElementGuid>90e242ac-9821-49fb-97ec-cc34c9dd2f29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='app-content']/div[2]/iframe</value>
      <webElementGuid>8c0286c0-7b59-48a2-8ef3-bbb615c9b668</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>85a4e318-0699-4209-a544-eb344a722937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ember179' and @title = 'Notifications' and @src = '/web/Notifications/NotificationsNew.aspx']</value>
      <webElementGuid>08e19c0e-6c4a-4711-832b-4a56b4d4c252</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
