<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Add_form-control user-search first</name>
   <tag></tag>
   <elementGuidId>61f020db-ce93-46fc-8f76-8c32fc19d7f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.form-control.user-search.first</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ba72b424-5aae-40af-9728-28e55e37d561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>b682e8b0-3baa-447b-aaa0-473c8ecd8152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control user-search first</value>
      <webElementGuid>a3f25906-270d-4740-83d4-d438c0a404bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>26c7d158-b262-462a-8475-02850ed818a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_responsiveBody_notifications_divSearch&quot;)/div[@class=&quot;input-invisible-addon input-invisible-sm pre post&quot;]/input[@class=&quot;form-control user-search first&quot;]</value>
      <webElementGuid>fc8a6b39-d9f5-4795-ad6e-1f0a9cdc5b6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Notifications  Alarm.com/iframe_Notifications  Alarm.com has loaded_ember179</value>
      <webElementGuid>9b4c8aff-034e-4c86-a820-e96e4ed01763</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[5]</value>
      <webElementGuid>8d5c849b-8cd6-4bf8-a230-fcc1487679a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_responsiveBody_notifications_divSearch']/div/input</value>
      <webElementGuid>2f834fff-ce15-468e-9bc8-ef50eefde1de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>5f5a9f59-764a-44e2-986d-c99e598d2a4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @placeholder = 'Search']</value>
      <webElementGuid>9e53a2f4-a9b6-474d-809a-c6963a3442bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
